### ISSUE TITLE
[SubIssue 5.2] Setting Availability Algorithm

### ISSUE THREAD

**Issue by od-obas1187** [CSC207-2022F-UofT/course-project-schedulize#30]
(User Story)
First, through the HomeScreen, the user inputs their availability(ies), clicking Enter. Once that’s entered, the AvailabilityController is called with a set of LocalTime values representing when the user is available. This controller then calls the AvailabilityInputBoundary, which is implemented by AvailablityInteractor. The AvailabilityInputBoundary has a method named createAvailability() that creates a TimeManager that holds multiple TimeBlock items. After this is completed, the AvailabiltyInteractor passes an AvailabilityModel back to the AvailabityOutputBoundary, an interface implemented by the AvailablityPresenter. The presenter then passes the updated AvailabilityModel to the view model, which is then unpackaged for the dashboard to then present the information to the user through the UI. (The availability will be assigned to a schedule associated with the curriculum, thus linking the availability to the user)

**Comment by MMachadoUofT** [comment]
Similar to my other issue closing; all relevant pieces of this issue that were within the scope of development time we had left have been implemented, so I'll go ahead and wrap this issue up.
