### ISSUE TITLE
[Feature 9] Build Driver

### ISSUE THREAD

**Issue by MMachadoUofT** [CSC207-2022F-UofT/course-project-schedulize#48]
This issue is simply for whoever ends up being delegated to building the actual Driver for the program, i.e. the Main class that will build the whole architecture and run the login/registration use case to start with
- [ ] Create a Main class
- [ ] Create inMemoryUser container class
- [ ] Link inMemoryUser to user interactors

**Comment by dadler83** [comment]
I already had a version of a main class in my branch, which I extracted, and I created the InMemoryUser singleton as part of my use case. Everybody can link their work to those classes as they see fit. When my PR for branch #49 goes through, everyone will have these!
