### ISSUE TITLE
[Feature 5] Setting Availability Algorithm

### ISSUE THREAD

**Issue by bmguiler** [CSC207-2022F-UofT/course-project-schedulize#5]
Create the Schedule class that will be held by each user (which will hold the user's availability and curriculums), and implement the algorithm for when a user is adding their **availability**

- [x] #25 
- [x] #30

**Comment by MMachadoUofT** [comment]
Create the Schedule class that will be held by each user, and that will hold the user's availability and curriculums, and implement the scheduling algorithm for when a user is creating a new curriculum

- [ ] Schedule class
- [ ] Curriculum scheduling algorithm

**Comment by MMachadoUofT** [comment]
Since we decided to simplify this piece of the project, and all availability-related code is on main, I'll go ahead and close this issue.
